### ISSUE TITLE
cannot Configure the learn-co gem on Cloud9

### ISSUE THREAD

**Issue by Madalinesh** [learn-co-curriculum/cloud9-aws-environment-setup#1]

**Comment by ihollander** [comment]
Hi @Madalinesh, the AWS Cloud9 environment is only intended to be used as a temporary environment if you're not able to set up your local environment, but we strongly recommend setting up your Mac or Windows environment instead of AWS Cloud9 as soon as you are able to. Instructions for setting up your local environment can be found in the Prework or Homeroom courses in Canvas.
